// Generated by CoffeeScript 1.6.3
(function() {
  var addersubber, enders, flatSplat, helpers, inDir, inLib, misc, moment, momentous, oneRand, partial2, path, predicates, printem, randDates, randoms, reverse2, selectors, sorters, starters, toStrings, _, _ref,
    __slice = [].slice;

  moment = require("moment");

  _ = require("underscore");

  path = require("path");

  _ref = require(path.join(__dirname, "lib/util.js")), reverse2 = _ref.reverse2, partial2 = _ref.partial2, flatSplat = _ref.flatSplat, inDir = _ref.inDir;

  inLib = inDir(path.join(__dirname, "lib"));

  momentous = {};

  predicates = require(inLib("predicates.js"));

  _.extend(momentous, predicates);

  selectors = require(inLib("selectors.js"));

  _.extend(momentous, selectors);

  addersubber = require(inLib("addersubber.js"));

  _.extend(momentous, addersubber);

  starters = require(inLib("starters.js"));

  _.extend(momentous, starters);

  enders = require(inLib("enders.js"));

  _.extend(momentous, enders);

  sorters = require(inLib("sorters.js"));

  momentous.sort = sorters.ascending;

  _.extend(momentous.sort, sorters);

  helpers = require(inLib("helpers.js"));

  _.extend(momentous, helpers);

  randoms = require(inLib("random.js"));

  _.extend(momentous, randoms);

  misc = require(inLib("misc.js"));

  oneRand = (function() {
    var fiveYears, now, _diff;
    now = moment();
    fiveYears = momentous.add.years(now, 5);
    _diff = misc.absDiff(now, fiveYears);
    return function() {
      var diffAmt, sign, _diffAmt, _rnd;
      _rnd = Math.random();
      diffAmt = _diff * _rnd;
      sign = Math.random();
      if (sign < 0.5) {
        _diffAmt = _diffAmt * -1;
      }
      return momentous.add(now, diffAmt);
    };
  })();

  randDates = function(dateCount) {
    var _outs;
    if (dateCount == null) {
      dateCount = 12;
    }
    _outs = [];
    while (dateCount--) {
      _outs.push(oneRand());
    }
    return _outs;
  };

  toStrings = function() {
    var dateList, _strung;
    dateList = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (_.isArray(dateList[0])) {
      dateList = dateList[0];
    }
    _strung = _.map(dateList, function(oneDate) {
      return oneDate.format();
    });
    return _strung;
  };

  printem = function(dateList) {
    return console.log(toStrings(eList));
  };

  module.exports = momentous;

}).call(this);
