// Generated by CoffeeScript 1.6.3
(function() {
  var enders, flatSplat, partial2, path, reverse2, _, _ref;

  path = require("path");

  _ref = require(path.join(__dirname, "util.js")), reverse2 = _ref.reverse2, partial2 = _ref.partial2, flatSplat = _ref.flatSplat;

  _ = require("underscore");

  enders = (function() {
    var _enders, _outs, _stringEndOf;
    _enders = ["Year", "Month", "Week", "Day", "Hour", "Minute", "Second"];
    _outs = {};
    _.each(_enders, function(oneEnder) {
      var _fnKey, _lcased;
      _fnKey = "endOf" + oneEnder;
      _lcased = oneEnder.toLowerCase();
      return _outs[_fnKey] = function(targetMoment) {
        return targetMoment.clone().endOf(_lcased);
      };
    });
    _stringEndOf = function(endString, targetMoment) {
      return targetMoment.clone().endOf(endString);
    };
    _outs.endOf = partial2(_stringEndOf);
    _outs.endOfMoment = partial2(reverse2(_stringEndOf));
    return _outs;
  })();

  module.exports = enders;

}).call(this);
