// Generated by CoffeeScript 1.6.3
/*

***	NOT CURRENTLY IN USE ****
*/


(function() {
  var flatSplat, getters, partial2, path, reverse2, _, _ref;

  path = require("path");

  _ref = require(path.join(__dirname, "util.js")), reverse2 = _ref.reverse2, partial2 = _ref.partial2, flatSplat = _ref.flatSplat;

  _ = require("underscore");

  getters = (function() {
    var _getString, _getters, _outs;
    _getters = ["unix", "valueOf", "daysInMonth", "isDST", "isLeapYear", "isMoment", "dayOfYear", "isoWeekday", "isoWeekYear", "weekYear", "week", "year", "isoWeek", "month"];
    _getString = function(methodName, targetMoment) {
      return targetMoment[methodName]();
    };
    _outs = {};
    _outs.get = partial2(_getString);
    _outs.getFrom = partial2(reverse2(_getString));
    _.each(_getters, function(oneGetter) {
      return _outs.get[oneGetter] = function(targetMoment) {
        return targetMoment[oneGetter]();
      };
    });
    return _outs;
  })();

  module.exports = getters;

}).call(this);
