// Generated by CoffeeScript 1.6.3
(function() {
  var checkMoment, flatSplat, moment, partial2, partial3, path, preds, reverse2, xyz_from_yzx, _, _ref;

  path = require("path");

  _ref = require(path.join(__dirname, "util.js")), reverse2 = _ref.reverse2, partial2 = _ref.partial2, partial3 = _ref.partial3, flatSplat = _ref.flatSplat;

  _ = require("underscore");

  moment = require("moment");

  checkMoment = function(possibleMoment) {
    if (moment.isMoment(possibleMoment)) {
      return possibleMoment;
    }
    return moment(possibleMoment);
  };

  xyz_from_yzx = function(fn) {
    return function(y, z, x) {
      return fn(x, y, z);
    };
  };

  preds = (function() {
    var isAfter, isAfterDate, isAfterMoment, isBefore, isBeforeData, isBeforeMoment, isBetween, isBetweenMoments, out, _isAfter, _isBefore, _isBetween;
    _isBetween = function(possiblyBetween, beforeMoment, afterMoment) {
      beforeMoment = checkMoment(beforeMoment);
      afterMoment = checkMoment(afterMoment);
      if (beforeMoment.isBefore(possiblyBetween) || beforeMoment.isSame(possiblyBetween)) {
        if (possiblyBetween.isBefore(afterMoment)) {
          return true;
        }
      }
      return false;
    };
    isBetween = partial3(_isBetween);
    isBetweenMoments = partial3(xyz_from_yzx(_isBetween));
    _isAfter = function(compare, compareAgainst) {
      compare = checkMoment(compare);
      if (compare.isAfter(compareAgainst)) {
        return true;
      }
      return false;
    };
    isAfter = partial2(_isAfter);
    isAfterMoment = partial2(reverse2(_isAfter));
    isAfterDate = isAfterMoment;
    _isBefore = function(compare, compareAgainst) {
      compare = checkMoment(compare);
      if (compare.isBefore(compareAgainst)) {
        return true;
      }
      return false;
    };
    isBefore = partial2(_isBefore);
    isBeforeMoment = partial2(reverse2(isBefore));
    isBeforeData = isBeforeMoment;
    return out = {
      isBetween: isBetween,
      isBetweenMoments: isBetweenMoments,
      isAfter: isAfter,
      isAfterMoment: isAfterMoment,
      isAfterDate: isAfterMoment,
      isBefore: isBefore,
      isBeforeMoment: isBeforeMoment,
      isBeforeDate: isBeforeMoment
    };
  })();

  module.exports = preds;

}).call(this);
