// Generated by CoffeeScript 1.6.3
(function() {
  var flatSplat, partial2, path, reverse2, starters, _, _ref;

  path = require("path");

  _ref = require(path.join(__dirname, "util.js")), reverse2 = _ref.reverse2, partial2 = _ref.partial2, flatSplat = _ref.flatSplat;

  _ = require("underscore");

  starters = (function() {
    var _outs, _starters, _stringStartOf;
    _starters = ["Year", "Month", "Week", "Day", "Hour", "Minute", "Second"];
    _outs = {};
    _.each(_starters, function(oneStarter) {
      var _fnKey, _lcased;
      _fnKey = "startOf" + oneStarter;
      _lcased = oneStarter.toLowerCase();
      return _outs[_fnKey] = function(targetMoment) {
        return targetMoment.clone().startOf(_lcased);
      };
    });
    _stringStartOf = function(startString, targetMoment) {
      return targetMoment.clone().startOf(startString);
    };
    _outs.startOf = partial2(_stringStartOf);
    _outs.startOfMoment = partial2(reverse2(_stringStartOf));
    return _outs;
  })();

  module.exports = starters;

}).call(this);
