// Generated by CoffeeScript 1.6.3
(function() {
  var Handlebars, fs, methods, _, _names;

  Handlebars = require("handlebars");

  fs = require("fs");

  _ = require("underscore");

  _names = ["Year", "Month", "Week", "Day", "Hour", "Minute", "Second"];

  methods = _.map(_names, function(aName) {
    return {
      method: "endOf" + aName,
      unit: aName.toLowerCase()
    };
  });

  fs.readFile("./endspec.hbs", "utf8", function(err, cont) {
    var locals, rendered, tmpl;
    tmpl = Handlebars.compile(cont);
    locals = {
      toTest: methods
    };
    rendered = tmpl(locals);
    return fs.writeFile("./enders.coffee", rendered, function(err) {
      return console.log("written");
    });
  });

}).call(this);
